# FILE: k8s/overlays/canary/canary-patch.yaml
# PURPOSE: Strategic merge patch that overrides env vars on the canary product-service
#          deployment to enable fault injection and mark metrics with version=canary.

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-gateway # matches the base. only the env vars change
  namespace: canary-app
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          env:
            - name: FAILURE_RATE # difference from og pod
              value: "0.3"
            - name: VERSION # difference from og pod
              value: "canary"
# the rest of the config from /base/api-gateway-deployment.yaml gets added on because the changes in this file are the only things that get overwritten. the base file doesn't change itself its the pod that changes.