# FILE: helm/values-prometheus.yaml
# PURPOSE: Overrides for the kube-prometheus-stack Helm chart.
#          Install the chart with:
#          helm install monitoring prometheus-community/kube-prometheus-stack \
#            -n monitoring --create-namespace \
#            -f helm/values-prometheus.yaml

prometheus:
  prometheusSpec:
    retention: 24h # keeps 24 hours of data (for demo)
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard # auto provisions a volume so prometheus data survives pod restarts (not cluster restart)
          resources:
            requests:
              storage: 5Gi
    additionalScrapeConfigs: # with only 2 services, additionalScrapeConfigs wins on simplicity. at 20+ services across multiple teams, ServiceMonitors win because no single person can track everything that needs to be scraped
      - job_name: api-gateway
        static_configs:
          - targets: ["api-gateway.canary-app.svc.cluster.local:8000"]
      - job_name: product-service
        static_configs:
          - targets: ["product-service.canary-app.svc.cluster.local:8001"]
grafana:
  adminPassword: "admin"