# FILE: k8s/base/namespace.yaml
# PURPOSE: Creates the namespaces that isolate app resources from monitoring resources.

apiVersion: v1
kind: Namespace
metadata:
  name: canary-app

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  